- hosts: localhost
  gather_facts: no
  vars:
    tower_user: admin
    tower_pass: password
    tower_host: ansibletower.knowcloud.in
    tower_job: "{{ 'pintest' | urlencode }}"
  vars_files:
    secret.yml
  tasks:
  - name: Host Ping Check
    failed_when: false
    ping:
    register: var_ping

  - name: launch a tower_job
    uri:
      url: https://{{ tower_host }}/api/v2/job_templates/{{ tower_job }}/launch/
      method: POST
      validate_certs: no
      return_content: yes
      user: "{{ tower_username }}"
      password: "{{ tower_password }}"
      force_basic_auth: yes
      status_code: 201

    