- hosts: managed1
  gather_facts: no

  tasks:
  - name: Host Ping Check
    failed_when: false
    ping:
    register: var_ping

  - name: create a list using the survey variable
    set_fact:
      srv_list: "{{ service_list.split('\n') }}"

  - name: Print the list type
    debug: msg="{{ srv_list|type_debug }}"


  - name: loop the list
    debug:
      msg: "{{ item }}"
    loop: "{{srv_list}}"
    loop_control:
       extended: yes

  - name: search the string matching hostname
    set_fact:
      host_matched_str: "{{ srv_list|select('match', '*managed1*') }}"

  - name: print the matched string
    debug:
      var: host_matched_str
