- name: Getting the definition of awesome
  hosts: localhost
  vars:
    file_name: "itm.zip"
    playbook_name: "webhook.yml"
    comment: "Hi, this message is for attachment testing"
    target: "ansible-job-notification"
    webhook_url: "https://kyndryl.webhook.office.com/webhookb2/9d74ff56-fab0-4087-a164-69623ca7af2f@f260df36-bc43-424c-8f44-c85226657b01/IncomingWebhook/13ad2dd6a27e4372a0fd37a85618acaf/57f58fc4-ba8c-40c2-bc82-df255cff53da"
  tasks:
  - name: test webhook connectivity
    uri:
      url: "{{ webhook_url }}"
      method: POST
      status_code: 200
      body_format: json
      body: |
        {
          "title": "Ansible notification message",
          "text": "play: {{ playbook_name }}, target: {{ target }}, comment: {{ comment }}"
        }

  - name: Call upload endpoints
    uri:
      url: ""https://kyndryl.webhook.office.com/webhookb2/9d74ff56-fab0-4087-a164-69623ca7af2f@f260df36-bc43-424c-8f44-c85226657b01/IncomingWebhook/13ad2dd6a27e4372a0fd37a85618acaf/57f58fc4-ba8c-40c2-bc82-df255cff53da"
      method: "POST"
      body_format: "form-multipart"
      body:
        backup:
          filename: "{{file_name}}"
          mime_type: application/octet-stream
        anotherFormParam: "api_key"
      force_basic_auth: yes
      return_content: yes
      headers:
        Content-Type: multipart/form-data
      validate_certs: false
    register: upload_result