- hosts: all
  gather_facts: no

  tasks:
  - name: Host Ping Check
    failed_when: false
    ping:
    register: var_ping

  - name: display ping results
    debug:
      var: var_ping

  - debug:
      var: ansible_play_hosts_all
  - debug:
      var: ansible_play_hosts
  - set_fact:
      down: "{{ ansible_play_hosts_all|difference(ansible_play_hosts) }}"
  - debug:
      var: down

- name: Play No.2
  hosts: all
  gather_facts: no
  tasks:
  - name: Host Ping Check
    win_ping:
    register: var_ping1
  - set_fact:
      down: "{{ ansible_play_hosts_all|difference(ansible_play_hosts) }}"
  - debug:
      var: down