- hosts: all
  gather_facts: no

  tasks:
  - name: Host Ping Check
    failed_when: false
    ping:
    register: var_ping

  - name: display ping results
    debug:
      var: var_ping

  - debug:
      var: ansible_play_hosts_all
  - debug:
      var: ansible_play_hosts
  - set_fact:
      down: "{{ ansible_play_hosts_all|difference(ansible_play_hosts) }}"
  - debug:
      var: down

 
  - ping:
    register: ping_out
    # one can include any kind of timeout or other stall related config here

  - debug:
      msg: |
        {% for k in hostvars.keys() %}
        {{ k }}: {{ hostvars[k].ping_out.unreachable|default(False) }}
        {% endfor %}