- hosts: managed1
  gather_facts: yes

  tasks:
  - name: Host Ping Check
    failed_when: false
    ping:
    register: var_ping


  - name: Comment the line CT_CMSLIST
    lineinfile: 
      path: /home/arunsippy/lu.ini
      backup: yes
      search_string: CT_CMSLIST
      line: CT_CMSLIST=IP.SPIPE:#10.174.225.54;IP.SPIPE:#10.174.225.47
      
      
     

  