- hosts: managed1
  gather_facts: yes
  
  handlers:
  - name: chk_changed_file
    become: yes
    become_user: root
    shell: |
      grep CT_CMSLIST /home/arunsippy/lu.ini
      cat /home/arunsippy/lu.ini
  tasks:
  - name: Host Ping Check
    failed_when: false
    ping:
    register: var_ping


  - name: Comment the line CT_CMSLIST
    lineinfile: 
      path: /home/arunsippy/lu.ini
      backup: yes
      regexp: CT_CMSLIST
      line: CT_CMSLIST=IP.SPIPE:#10.174.225.54;IP.SPIPE:#10.174.225.47
    notify: chk_changed_file
    register: res_lu_update

  - name: chk status of the res_lu_update
    debug:
      var: res_lu_update
   
      
      
     

  