- hosts: managed1
  gather_facts: yes
  
  handlers:
  - name: chk_changed_file_lu
    become: yes
    become_user: root
    shell: |
      grep CT_CMSLIST /home/arunsippy/lu.ini
      cat /home/arunsippy/lu.ini
      touch handlerchk.txt
    register: res_lu_handler

  


  tasks:
  - name: Host Ping Check
    failed_when: false
    ping:
    register: var_ping

  - name: To chk the handler error gets reported in rescue block
    block: 
    - name: Comment the line CT_CMSLIST
      lineinfile: 
        path: /home/arunsippy/lu.ini
        backup: yes
        regexp: CT_CMSLIST
        line: CT_CMSLIST=IP.SPIPE:#10.174.225.54;IP.SPIPE:#10.174.225.47
      register: res_lu_update
      notify: chk_changed_file_lu

    - meta: flush_handlers
      
    - name: chk status of the res_lu_handler
      debug:
        var: res_lu_handler

    rescue: 

    - name: Display the failed task
      debug:
        var: ansible_failed_task
       
    - name: Create Failed report when task failed
      copy:
        content: "{{inventory_hostname}},{{ansible_failed_task.name|default('Check for Failed Task',True)}},'Installation Failed'\n"
        dest: "/home/arunsippy/rtemsreport.txt"



  
   
      
      
     

  