- hosts: managed1
  gather_facts: yes
  
  handlers:
  - name: chk_changed_file_lu
    become: yes
    become_user: root
    shell: |
      grep CT_CMSLIST /home/arunsippy/lu.ini
      cat /home/arunsippy/lu.ini

  - name: chk_changed_file_lz
    become: yes
    become_user: root
    shell: |
      grep CT_CMSLIST /home/arunsippy/lz.ini
      cat /home/arunsippy/lz.ini


  tasks:
  - name: Host Ping Check
    failed_when: false
    ping:
    register: var_ping


  - name: Comment the line CT_CMSLIST
    lineinfile: 
      path: /home/arunsippy/lu.ini
      backup: yes
      regexp: CT_CMSLIST
      line: CT_CMSLIST=IP.SPIPE:#10.174.225.54;IP.SPIPE:#10.174.225.47
    #notify: chk_changed_file_lu
    register: res_lu_update

  - name: chk status of the res_lu_update
    debug:
      var: res_lu_update

  - name: Comment the line CT_CMSLIST in lz
    lineinfile: 
      path: /home/arunsippy/lz.ini
      backup: yes
      regexp: CT_CMSLIST
      line: CT_CMSLIST=IP.SPIPE:#10.174.225.54;IP.SPIPE:#10.174.225.47
    #notify: chk_changed_file_lz
    register: res_lz_update

  - name: chk status of the res_lu_update
    debug:
      var: res_lz_update

  - name: Comment the line CT_CMSLIST in ou
    lineinfile: 
      path: /home/arunsippy/ou.ini
      backup: yes
      regexp: CT_CMSLIST
      line: CT_CMSLIST=IP.SPIPE:#10.174.225.54;IP.SPIPE:#10.174.225.47
    notify: chk_changed_file_ou
    register: res_ou_update

  - name: chk status of the res_ou_update
    debug:
      var: res_ou_update
   
      
      
     

  