- name: Getting the definition of awesome
  hosts: localhost
  tasks:

  - uri:
      url: https://api.chucknorris.io/jokes/random
      method: GET
    register: results

  - debug:
      var: results